#!/usr/bin/env python3
"""
A-Evolve Engine v2 — First-Principles Self-Improvement Loop

Architecture: Observe → Diagnose → Mutate → Gate → Commit
Research basis: Voyager, A-Evolve, SkillForge, SkillAudit, SkillOpt, R-Zero

Key design decisions:
  - Bounded edits only (never full rewrite)
  - Diagnosis before prescription (5 failure modes → 4 strategies)
  - 3-layer gate (pre-check, benchmark, structural)
  - EGL convergence detection
  - Every mutation reversible via git snapshot
"""

import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ─── Configuration ───────────────────────────────────────────────────────────

SCRIPTS_DIR = Path(__file__).parent
SKILLS_DIR = SCRIPTS_DIR.parent / "skills"
EVO_DIR = SCRIPTS_DIR.parent / "skill_evo"
SNAPSHOTS_DIR = EVO_DIR / "snapshots"
TRAJECTORIES_DIR = EVO_DIR / "trajectories"
DIAGNOSIS_DIR = EVO_DIR / "diagnosis"

STATE_FILE = EVO_DIR / "state.json"
MUTATIONS_LOG = EVO_DIR / "mutations.jsonl"
GATE_LOG = EVO_DIR / "gate_results.jsonl"

# Gate thresholds
MIN_DELTA = 0.05          # Minimum benchmark improvement to accept (5%)
REGRESSION_TOLERANCE = 0.05  # Max allowed regression on non-target benchmarks
MAX_MUTATION_RATIO = 0.20  # Mutation can add at most 20% of file size
CONVERGENCE_EGL = 0.02     # EGL below this for N cycles = converged
CONVERGENCE_PATIENCE = 3   # Cycles below threshold before convergence

# Failure mode → strategy mapping
FAILURE_MODES = {
    "knowledge_gap": {
        "signal": "mentions concepts without defining them",
        "strategy": "repair",
        "priority": 1,
    },
    "missing_tool_step": {
        "signal": "describes workflow but no tool calls",
        "strategy": "repair",
        "priority": 2,
    },
    "missing_structure": {
        "signal": "disorganized or missing heading hierarchy",
        "strategy": "extend",
        "priority": 3,
    },
    "missing_edge_cases": {
        "signal": "missing error handling or edge cases",
        "strategy": "extend",
        "priority": 4,
    },
    "verbose_fluff": {
        "signal": "overly verbose with generic statements",
        "strategy": "compress",
        "priority": 5,
    },
    "actionability_gap": {
        "signal": "low code blocks, tool calls, commands vs generic prose",
        "strategy": "actionability_patch",
        "priority": 0,
    },
}

# Generic content patterns (tautology detection)
GENERIC_PATTERNS = [
    r"this\s+skill\s+provides\s+actionable\s+guidance",
    r"identify\s+the\s+task\s+context",
    r"follow\s+best\s+practices",
    r"ensure\s+you\s+understand",
    r"carefully\s+consider\s+the\s+requirements",
    r"it\s+is\s+important\s+to\s+note",
    r"in\s+order\s+to\s+achieve",
    r"leverage\s+your\s+expertise",
]

# Vague filler words/phrases that signal low-information content
_FILLER_WORDS = {
    "key features", "important functionality", "for users", "efficiently",
    "effectively", "daily workflow", "tasks and operations", "optimal results",
    "seamless experience", "robust solution", "comprehensive approach",
    "leverage", "synergy", "paradigm", "holistically", "actionable insights",
    "best in class", "cutting edge", "state of the art", "world class",
}


# ─── State Management ────────────────────────────────────────────────────────

def load_state() -> dict:
    """Load evolution state from disk."""
    if STATE_FILE.exists():
        state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
        # Ensure migration fields exist
        state.setdefault("mutation_budget", {})  # skill -> {"count": int, "last_delta": float, "frozen": bool}
        return state
    return {
        "cycle": 0,
        "mutations_attempted": 0,
        "mutations_accepted": 0,
        "mutations_rejected": 0,
        "skills_converged": [],
        "skills_frozen": [],
        "egl_history": {},  # skill -> [egl values]
        "post_mutation_scores": {},  # skill -> overall_score after last mutation
        "last_target": None,
        "mutation_budget": {},  # skill -> {"count": int, "last_delta": float, "frozen": bool}
    }


def save_state(state: dict):
    """Persist evolution state."""
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


# ─── Episodic Memory ──────────────────────────────────────────────────────────

EPISODIC_FILE = EVO_DIR / "episodic.jsonl"

def load_episodic_memory() -> dict[str, int]:
    """Load episodic memory and count failed strategy attempts.
    
    Reads episodic.jsonl (generated by extract_wisdom.py) and extracts
    strategy failures by name. Returns {strategy_name: failure_count}.
    Used to blacklist failing strategies during strategy selection.
    """
    failures: dict[str, int] = {}
    if not EPISODIC_FILE.exists():
        return failures
    for line in EPISODIC_FILE.read_text(encoding="utf-8").strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        # Extract strategy from various episodic formats
        strategy = entry.get("strategy") or entry.get("diagnosis") or entry.get("mode")
        if strategy:
            failed = not entry.get("passed", True) or entry.get("gate_result") == "rejected"
            if failed:
                failures[strategy] = failures.get(strategy, 0) + 1
    return failures


# ─── Mutation Budget / Convergence ────────────────────────────────────────────

MAX_MUTATIONS_PER_SKILL = 5       # Hard cap on total mutations per skill
MIN_DELTA_TO_KEEP_BUDGET = 0.01   # Delta below this consumes budget without improvement

def check_mutation_budget(state: dict, skill_name: str, delta: float) -> bool:
    """Track per-skill mutation budget and return True if skill is over-budget.
    
    After 3 mutations with delta < 1%, the skill is frozen and budget rotates.
    After 5 total mutations, hard-freeze regardless of delta.
    """
    budget = state.setdefault("mutation_budget", {})
    if skill_name not in budget:
        budget[skill_name] = {"count": 0, "last_delta": 0.0, "frozen": False}
    
    budget[skill_name]["count"] += 1
    budget[skill_name]["last_delta"] = delta
    
    count = budget[skill_name]["count"]
    
    # Hard cap: max 5 mutations on any skill
    if count >= MAX_MUTATIONS_PER_SKILL:
        budget[skill_name]["frozen"] = True
        return True
    
    # Soft cap: if last 3 deltas were < 1%, freeze (check via egl_history)
    history = state.get("egl_history", {}).get(skill_name, [])
    recent = history[-3:] if len(history) >= 3 else history
    if len(recent) >= 3 and all(abs(e) < MIN_DELTA_TO_KEEP_BUDGET for e in recent):
        budget[skill_name]["frozen"] = True
        return True
    
    return False


def get_strategy_blacklist(episodic_failures: dict[str, int], threshold: int = 2) -> set[str]:
    """Return set of strategy names that have failed >= threshold times in episodic memory."""
    return {s for s, c in episodic_failures.items() if c >= threshold}


# ─── Benchmark Suite ─────────────────────────────────────────────────────────

def run_benchmarks(skill_path: Path) -> dict[str, float]:
    """
    Run all micro-benchmarks against a skill file.
    Returns dict of {benchmark_name: score_0_to_1}.
    """
    content = skill_path.read_text(encoding="utf-8")
    lines = content.strip().split("\n")
    word_count = len(content.split())
    
    # Separate frontmatter from body
    in_fm = False
    body_start = 0
    if content.startswith("---"):
        in_fm = True
        for i, line in enumerate(lines[1:], 1):
            if line.strip() == "---":
                in_fm = False
                body_start = i + 1
                break
    body = "\n".join(lines[body_start:])
    body_lower = body.lower()
    
    results = {}
    
    # 1. Existence: file exists and has content
    results["existence"] = 1.0 if word_count > 50 else (word_count / 50)
    
    # 2. Structure: has required sections
    has_frontmatter = content.startswith("---")
    has_steps = bool(re.search(r"^#{1,3}\s+step", body, re.MULTILINE | re.IGNORECASE))
    has_references = "references" in body_lower or "reference" in body_lower
    has_pitfalls = "pitfall" in body_lower or "warning" in body_lower or "caution" in body_lower
    structure_score = sum([has_frontmatter, has_steps, has_references, has_pitfalls]) / 4
    results["structure"] = structure_score
    
    # 3. Actionability: has tool calls, commands, file paths
    code_blocks = len(re.findall(r"```", body))
    tool_calls = len(re.findall(r"tool[s]?\s*:|function[s]?\s*:|\bterminal\b|\bbrowser\b|\bweb_search\b", body_lower))
    file_paths = len(re.findall(r"[/\\][\w./\\-]+\.\w{2,4}", body))
    commands = len(re.findall(r"^\s*[`$#>]\s+\w", body, re.MULTILINE))
    actionability_score = min(1.0, (code_blocks * 0.15 + tool_calls * 0.1 + file_paths * 0.15 + commands * 0.1))
    results["actionability"] = actionability_score
    
    # 4. Specificity: domain-specific terms vs generic
    domain_terms = len(re.findall(r"\b(?:api|endpoint|schema|config|docker|git|python|json|yaml|http|sql|cli|sdk|token|auth|webhook|server|client|database|cache|queue)\b", body_lower))
    generic_count = sum(1 for p in GENERIC_PATTERNS if re.search(p, body_lower))
    specificity = min(1.0, domain_terms / 10) * (0.5 ** generic_count)
    results["specificity"] = specificity
    
    # 5. References: has reference files or links
    has_ref_section = bool(re.search(r"^#{1,3}\s+references?", body, re.MULTILINE | re.IGNORECASE))
    has_links = len(re.findall(r"\[.*?\]\(https?://.*?\)", body))
    has_external_refs = len(re.findall(r"see\s+also|refer\s+to|check\s+out", body_lower))
    ref_score = min(1.0, (has_ref_section * 0.4 + min(has_links, 5) * 0.1 + has_external_refs * 0.2))
    results["references"] = ref_score
    
    # 6. Content quality: ratio of signal to noise
    sentences = re.split(r"[.!?]+", body)
    meaningful_sentences = sum(1 for s in sentences if len(s.split()) > 5 and not any(re.search(p, s.lower()) for p in GENERIC_PATTERNS))
    total_sentences = max(1, len(sentences))
    results["content_quality"] = meaningful_sentences / total_sentences
    
    # 7. Domain-specific benchmarks (auto-discovered from skill_evo/benchmarks/ dir)
    bench_dir = Path(__file__).resolve().parent.parent / "skill_evo" / "benchmarks"
    if bench_dir.exists():
        for bench_file in sorted(bench_dir.glob("bench_*.py")):
            try:
                # Dynamic import via exec to avoid .pyc pollution
                import importlib.util
                spec = importlib.util.spec_from_file_location(f"bench_{bench_file.stem}", bench_file)
                if spec and spec.loader:
                    mod = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(mod)
                    if hasattr(mod, "run_benchmark"):
                        domain_result = mod.run_benchmark(content, skill_path)
                        # Prefix with domain name to avoid collision
                        prefix = bench_file.stem.replace("bench_", "")
                        for k, v in domain_result.items():
                            results[f"{prefix}_{k}"] = v
                del spec  # Cleanup module cache
            except Exception as e:
                print(f"    ⚠️  Domain benchmark {bench_file.name}: {e}")
    
    return results


def _walk_skills(skills_dir: Path) -> list[tuple[str, Path]]:
    """Recursively walk subdirectories and return (skill_name, skimmd_path) pairs.
    
    Discovers skills at any nesting depth — both top-level (skills/foo/SKILL.md)
    and nested under category dirs (skills/mlops/foo/SKILL.md). Skips known
    non-skill files (.bundled_manifest, .curator_state, etc.) and dirs that
    don't contain a SKILL.md.
    """
    found = []
    for entry in sorted(skills_dir.iterdir()):
        if not entry.is_dir():
            continue
        # Direct child — top-level skill
        md = entry / "SKILL.md"
        if md.exists():
            found.append((entry.name, md))
            continue
        # Category dir — walk subdirs for nested skills
        for sub in sorted(entry.iterdir()):
            if sub.is_dir():
                sub_md = sub / "SKILL.md"
                if sub_md.exists():
                    found.append((sub.name, sub_md))
    return found


def _build_skill_map(skills_dir: Path = None) -> dict[str, Path]:
    """Build a flat mapping of skill_name -> SKILL.md path.
    
    Covers all discovered skills at any nesting depth. Used by all functions
    that need to resolve a skill name to its filesystem path.
    """
    if skills_dir is None:
        skills_dir = SKILLS_DIR
    return {name: path for name, path in _walk_skills(skills_dir)}


def run_all_skills_benchmark() -> dict[str, dict[str, float]]:
    """Run benchmarks against all skills. Returns {skill_name: {benchmark: score}}.
    
    Recursively discovers skills at any nesting depth. Previously only found
    top-level skills (skills/<name>/SKILL.md), missing ~80 skills nested under
    category subdirectories (skills/mlops/<name>/SKILL.md).
    """
    results = {}
    for skill_name, skill_md in _walk_skills(SKILLS_DIR):
        results[skill_name] = run_benchmarks(skill_md)
    return results


def compute_overall_score(benchmarks: dict[str, float]) -> float:
    """Weighted overall score from individual benchmarks."""
    weights = {
        "existence": 0.05,
        "structure": 0.20,
        "actionability": 0.30,
        "specificity": 0.20,
        "references": 0.10,
        "content_quality": 0.15,
    }
    return sum(benchmarks.get(k, 0) * w for k, w in weights.items())


# ─── Diagnosis Engine ────────────────────────────────────────────────────────

def diagnose_skill(skill_name: str, benchmarks: dict[str, float], content: str) -> dict:
    """
    Diagnose WHY a skill scores low. Returns failure mode + recommended strategy.
    Rule-based classifier (v2.1 will use LLM for this).
    """
    body = content.lower()
    word_count = len(content.split())
    
    diagnoses = []
    
    # Check each failure mode
    if benchmarks.get("actionability", 0) < 0.2:
        diagnoses.append({
            "mode": "missing_tool_step",
            "confidence": 0.8,
            "evidence": f"actionability={benchmarks['actionability']:.2f}",
        })
    elif benchmarks.get("actionability", 0) < 0.5:
        # Check if it's an actionability_gap (has prose but zero code blocks/tools)
        code_blocks = len(re.findall(r"```", content))
        tool_calls = len(re.findall(r"tool[s]?\s*:|function[s]?\s*:", content.lower()))
        commands = len(re.findall(r"^[\s]*[`$#>]\s+\w", content, re.MULTILINE))
        if code_blocks == 0 and tool_calls == 0 and commands == 0:
            diagnoses.append({
                "mode": "actionability_gap",
                "confidence": 0.7,
                "evidence": f"actionability={benchmarks['actionability']:.2f}, code_blocks=0",
            })
        else:
            diagnoses.append({
                "mode": "missing_tool_step",
                "confidence": 0.6,
                "evidence": f"actionability={benchmarks['actionability']:.2f}",
            })
    
    if benchmarks.get("specificity", 0) < 0.3:
        diagnoses.append({
            "mode": "knowledge_gap",
            "confidence": 0.7,
            "evidence": f"specificity={benchmarks['specificity']:.2f}",
        })
    
    if benchmarks.get("structure", 0) < 0.5:
        diagnoses.append({
            "mode": "missing_structure",
            "confidence": 0.8,
            "evidence": f"structure={benchmarks['structure']:.2f}",
        })
    
    if benchmarks.get("content_quality", 0) < 0.5 and word_count > 200:
        diagnoses.append({
            "mode": "verbose_fluff",
            "confidence": 0.6,
            "evidence": f"content_quality={benchmarks['content_quality']:.2f}, words={word_count}",
        })
    
    if benchmarks.get("actionability", 0) > 0.3 and "error" not in body and "fail" not in body:
        diagnoses.append({
            "mode": "missing_edge_cases",
            "confidence": 0.5,
            "evidence": "no error handling or edge case coverage",
        })
    
    # Sort by priority
    diagnoses.sort(key=lambda d: FAILURE_MODES.get(d["mode"], {}).get("priority", 99))
    
    if not diagnoses:
        return None
    
    primary = diagnoses[0]
    strategy = FAILURE_MODES[primary["mode"]]["strategy"]
    
    return {
        "skill": skill_name,
        "primary_mode": primary["mode"],
        "strategy": strategy,
        "confidence": primary["confidence"],
        "evidence": primary["evidence"],
        "all_diagnoses": diagnoses,
    }


# ─── Mutation Strategies ─────────────────────────────────────────────────────

def _is_generic_content(text: str) -> bool:
    """Check if text is generic filler (tautology detection)."""
    text_lower = text.lower()
    generic_count = sum(1 for p in GENERIC_PATTERNS if re.search(p, text_lower))
    # Filler word density: count how many vague buzzwords appear
    filler_hits = sum(1 for fw in _FILLER_WORDS if fw in text_lower)
    # Also check for very short sentences (likely filler)
    sentences = [s.strip() for s in re.split(r"[.!?]+", text_lower) if s.strip()]
    short_sentences = sum(1 for s in sentences if len(s.split()) < 6)
    if sentences:
        short_ratio = short_sentences / len(sentences)
    else:
        short_ratio = 0
    
    return generic_count >= 2 or short_ratio > 0.7 or filler_hits >= 3


def _get_domain_terms(skill_name: str, desc_lower: str) -> str:
    """
    Map skill name/desc to domain-specific technical terminology.
    Returns markdown bullet list of domain terms.
    
    This bridges the gap between generic templates and domain-grounded content
    (SkillForge's key insight: evolution quality depends on domain grounding).
    """
    name_lower = skill_name.lower()
    
    # Domain keyword mapping — single-quoted to avoid ** conflicts
    # Covers all ~60 skill domains in the inventory
    domain_keywords = {
        # ─── Infrastructure / DevOps ──────────────────────────────────────
        'backup': ['- **Snapshot**: Point-in-time copy of data for recovery',
                 '- **Retention**: Policy defining how long backups are kept',
                 '- **Integrity**: Checksum/validation to verify backup completeness',
                 '- **Rollback**: Restore operation to revert to previous state'],
        'cron': ['- **Schedule**: Cron expression defining execution timing',
                 '- **Daemon**: Long-running process that triggers jobs',
                 '- **Heartbeat**: Periodic signal confirming service health',
                 '- **Idempotency**: Safe to re-run without side effects'],
        'monitor': ['- **Metric**: Quantitative measurement (CPU, memory, latency)',
                    '- **Alert**: Notification triggered by threshold breach',
                    '- **Dashboard**: Real-time visualization of system health',
                    '- **SLA**: Service level agreement defining uptime targets'],
        'observ': ['- **Trace**: End-to-end request path through distributed system',
                   '- **Log**: Timestamped record of system events',
                   '- **Span**: Single operation within a distributed trace',
                   '- **Cardinality**: Unique value count in time-series data'],
        'health': ['- **Check**: Automated probe verifying component health',
                   '- **Restart**: Graceful restart procedure for hung processes',
                   '- **Escalation**: Procedure when automated recovery fails',
                   '- **Watchdog**: Process that monitors and restarts failed daemons'],
        
        # ─── Data / Pipeline ──────────────────────────────────────────────
        'data': ['- **Schema**: Structure definition for data validation',
                 '- **Pipeline**: Sequence of data transformation steps',
                 '- **Ingestion**: Process of importing data from sources',
                 '- **ETL**: Extract, Transform, Load workflow pattern'],
        'ingest': ['- **Source**: Origin system or feed providing data',
                   '- **Parser**: Component that extracts structure from raw input',
                   '- **Queue**: Buffer for asynchronous data processing',
                   '- **Deduplication**: Removing duplicate records from input'],
        'silo': ['- **Namespace**: Logical partition isolating data domains',
                 '- **Index**: Data structure enabling fast lookups',
                 '- **Query**: Structured request to retrieve stored data',
                 '- **Migration**: Moving data between storage tiers'],
        'vector': ['- **Embedding**: Dense vector representation of semantic meaning',
                   '- **Similarity**: Cosine distance between embeddings',
                   '- **ANN**: Approximate Nearest Neighbor search algorithm',
                   '- **Dimensionality**: Number of components in the embedding vector'],
        
        # ─── GitHub / Version Control ──────────────────────────────────────
        'git': ['- **Branch**: Divergent line of development',
                '- **Commit**: Snapshot of changes with metadata',
                '- **PR (Pull Request)**: Proposed changes for review',
                '- **CI/CD**: Continuous Integration / Continuous Deployment'],
        'github': ['- **Issue**: Tracked bug, feature request, or task',
                   '- **Repository**: Project storage with version history',
                   '- **Webhook**: HTTP callback triggered by repo events',
                   '- **Release**: Tagged version with changelog'],
        'version': ['- **SemVer**: Semantic versioning (major.minor.patch)',
                    '- **Changelog**: Record of changes between versions',
                    '- **Rollback**: Revert to previous known-good version',
                    '- **Tag**: Named reference to specific commit'],
        
        # ─── AI / ML / Model Management ────────────────────────────────────
        'model': ['- **Inference**: Forward pass through a neural network',
                  '- **Quantization**: Reducing precision (FP16→INT4) for speed',
                  '- **Context Window**: Max tokens the model can process',
                  '- **VRAM**: GPU memory required to load and run the model'],
        'llm': ['- **Prompt**: Input text conditioning model output',
                '- **Token**: Subword unit the model processes',
                '- **Temperature**: Sampling randomness parameter',
                '- **System Prompt**: Persistent instructions prepended to every query'],
        'ml': ['- **Training**: Process of fitting model parameters to data',
               '- **Validation**: Held-out dataset for hyperparameter tuning',
               '- **Overfitting**: Model memorizes training data, fails to generalize',
               '- **Batch Size**: Number of samples processed before weight update'],
        'vllm': ['- **PagedAttention**: Memory management for KV-cache fragmentation',
                 '- **Throughput**: Tokens generated per second across all requests',
                 '- **Continuous Batching**: Dynamic batching without padding waste',
                 '- **Tensor Parallelism**: Splitting model weights across GPUs'],
        'inference': ['- **Latency**: Time from request to first token',
                      '- **Throughput**: Tokens per second sustained',
                      '- **KV-Cache**: Stored attention keys/values to avoid recomputation',
                      '- **Batching**: Grouping requests to maximize GPU utilization'],
        
        # ─── Wisdom / Knowledge / Self-Evaluation ──────────────────────────
        'wisdom': ['- **Extraction**: Distilling principles from experience',
                   '- **Distillation**: Condensing large content to essentials',
                   '- **Pattern**: Recurring structure across sessions',
                   '- **Heuristic**: Practical rule-of-thumb for decision-making'],
        'memory': ['- **Episodic**: Memory of specific events and experiences',
                   '- **Semantic**: General knowledge and facts',
                   '- **Retrieval**: Finding relevant memories for current context',
                   '- **Forgetting**: Natural decay of unused memories'],
        'self-eval': ['- **OODA**: Observe, Orient, Decide, Act decision loop',
                      '- **Calibration**: How well confidence matches accuracy',
                      '- **Bias**: Systematic deviation from correct behavior'],
        'vault': ['- **Node**: Atomic unit of knowledge in the vault graph',
                  '- **Edge**: Link between related vault entries',
                  '- **Frontmatter**: YAML metadata block at the top of a note',
                  '- **Bidirectional Link**: Both nodes reference each other'],
        'reflection': ['- **Introspection**: Examining one\'s own decision process',
                        '- **Meta-cognition**: Thinking about thinking patterns',
                        '- **Course Correction**: Adjusting trajectory based on reflection'],
        
        # ─── Security / Testing ────────────────────────────────────────────
        'test': ['- **Assertion**: Condition that must hold true',
                 '- **Fixture**: Fixed baseline for reproducible testing',
                 '- **Mock**: Simulated dependency for isolation',
                 '- **Coverage**: Percentage of code paths exercised by tests'],
        'audit': ['- **Compliance**: Adherence to policy or regulation',
                  '- **Trail**: Chronological record of all actions',
                  '- **Non-repudiation**: Proof that action occurred and by whom'],
        'auth': ['- **Credential**: Token or key proving identity',
                  '- **Scope**: Permission boundaries for an authenticated entity',
                  '- **Rotation**: Periodic replacement of credentials',
                  '- **Least Privilege**: Granting minimum necessary permissions'],
        
        # ─── Communication / Social / Web ──────────────────────────────────
        'post': ['- **Engagement**: Likes, replies, reposts on content',
                 '- **Thread**: Sequence of connected posts',
                 '- **Mention**: Reference to another user via @handle'],
        'browser': ['- **DOM**: Document Object Model tree structure',
                    '- **Selector**: CSS/XPath expression to find elements',
                    '- **Snapshot**: Accessibility tree representation'],
        'email': ['- **IMAP**: Protocol for retrieving email from a server',
                  '- **SMTP**: Protocol for sending email',
                  '- **Folder**: Organizational container for messages',
                  '- **Filter**: Rule-based automatic email sorting'],
        'social': ['- **Feed**: Chronological or algorithmic content stream',
                   '- **Profile**: User identity page with metadata',
                   '- **Moderation**: Process of reviewing content for policy violations'],
        'x': ['- **Tweet**: Single post on X (Twitter)',
               '- **Retweet**: Sharing another user\'s tweet with followers',
               '- **Reply**: Response to a tweet, visible in conversation thread'],
        
        # ─── Hermes / Agent Infrastructure ─────────────────────────────────
        'hermes': ['- **Skill**: Reusable procedure with frontmatter metadata',
                   '- **Toolset**: Group of related tools available to the agent',
                   '- **Cron**: Scheduled recurring task with prompt + skills',
                   '- **Profile**: Isolated configuration with own skills/memories/cron'],
        'skill-evo': ['- **Mutation**: Bounded edit to an existing skill',
                       '- **Gate**: Multi-layer validation before accepting mutation',
                       '- **EGL**: Exponential Growth Lambda convergence metric',
                       '- **Snapshot**: Pre-mutation backup enabling rollback'],
        'agent': ['- **Orchestrator**: Top-level agent coordinating sub-agents',
                 '- **Leaf**: Worker sub-agent that cannot delegate further',
                 '- **Swarm**: Multiple agents collaborating on shared task',
                 '- **Context Window**: Available token space for agent reasoning'],
        'autonom': ['- **Self-correction**: Detecting and fixing own errors without user input',
                    '- **Goal decomposition**: Breaking objectives into actionable sub-tasks',
                    '- **Execution discipline**: Completing all steps before reporting success'],
        
        # ─── Productivity / Notes ──────────────────────────────────────────
        'obsidian': ['- **Vault**: Root folder containing all notes and config',
                     '- **Wikilink**: Double-bracket syntax `[[note]]` for internal links',
                     '- **Plugin**: Community extension adding functionality',
                     '- **Dataview**: Query language for dynamic note collections'],
        'kanban': ['- **Card**: Single task on the board',
                   '- **Column**: Stage in the workflow (Todo, In Progress, Done)',
                   '- **WIP Limit**: Max cards in a column to prevent overload',
                   '- **Sprint**: Time-boxed work cycle with defined goals'],
        
        # ─── Creative / Media ──────────────────────────────────────────────
        'image': ['- **Prompt**: Text description for image generation',
                  '- **Seed**: Random number controlling generation reproducibility',
                  '- **CFG Scale**: Classifier-Free Guidance — prompt adherence strength',
                  '- **Sampler**: Noise scheduling algorithm (euler, dpmpp)'],
        'comfyui': ['- **Node**: Processing unit in the ComfyUI graph',
                    '- **Workflow**: DAG of nodes defining the image pipeline',
                    '- **Checkpoint**: Trained model file (SD1.5, SDXL, FLUX)',
                    '- **VAE**: Variational Autoencoder for latent space conversion'],
        'music': ['- **MIDI**: Musical Instrument Digital Interface protocol',
                  '- **Tempo**: Beats per minute defining playback speed',
                  '- **Timbre**: Tonal quality distinguishing different instruments',
                  '- **Chord Progression**: Sequence of harmonic structures'],
        
        # ─── Research ──────────────────────────────────────────────────────
        'research': ['- **Peer Review**: Expert evaluation before publication',
                     '- **Reproducibility**: Ability to replicate experimental results',
                     '- **Citation**: Reference to prior work supporting claims',
                     '- **Literature Survey**: Comprehensive review of existing work'],
        'arxiv': ['- **Preprint**: Paper before formal peer review',
                  '- **Abstract**: Concise summary of the paper\'s contributions',
                  '- **DOI**: Digital Object Identifier for permanent citation'],
        
        # ─── Smart Home / IoT ──────────────────────────────────────────────
        'home': ['- **Hub**: Central controller coordinating smart devices',
                 '- **Zigbee**: Low-power mesh protocol for IoT devices',
                 '- **Scene**: Predefined configuration of multiple device states',
                 '- **Automation**: Rule: "if sensor X, then action Y"'],
        
        # ─── Backup / Restore ──────────────────────────────────────────────
        'restore': ['- **Verification**: Confirming restored data matches source',
                    '- **Point-in-Time**: Restoring to a specific moment, not latest',
                    '- **Partial Restore**: Recovering a subset of data, not everything'],
        
        # ─── Loop Detection / Anti-Pattern ─────────────────────────────────
        'loop': ['- **Cycle**: Repeated execution without progress condition',
                 '- **Stagnation**: Agent repeating same approach expecting different result',
                 '- **Escalation Threshold**: Max retries before human intervention required',
                 '- **Convergence**: Successive iterations produce diminishing changes'],
        'iteration': ['- **Guardrail**: Runtime check that aborts if limits exceeded',
                       '- **Retry Budget**: Max attempts before escalating to human',
                       '- **Backtracking**: Reverting to last valid state when iteration fails',
                       '- **Progress Condition**: Measurable signal that iteration is advancing'],
        'error': ['- **Exception**: Runtime error interrupting normal execution',
                 '- **Stack Trace**: Call hierarchy showing error origin',
                 '- **Graceful Degradation**: Continuing with reduced functionality after error'],
        
        # ─── Logging / Resilience ──────────────────────────────────────────
        'log': ['- **Severity**: Level indicating importance (DEBUG, INFO, WARN, ERROR)',
                '- **Appender**: Destination where log entries are written',
                '- **Rotation**: Archiving old logs to prevent disk exhaustion'],
        'retry': ['- **Exponential Backoff**: Doubling wait time between retry attempts',
                  '- **Circuit Breaker**: Failing fast when downstream is unhealthy',
                  '- **Dead Queue**: Storage for messages that exceeded retry limit'],
    }
    
    # Find matching domain
    matched_terms = []
    for keyword, terms in domain_keywords.items():
        if keyword in name_lower or keyword in desc_lower:
            matched_terms = terms
            break
    
    # Fallback: generate from skill name words
    if not matched_terms:
        words = [w for w in desc_lower.split() if len(w) > 3]
        matched_terms = [
            f'- **{w.title()}**: Core concept in this skill domain'
            for w in words[:4]
        ]
    
    return '\n'.join(matched_terms)


def generate_mutation(skill_name: str, strategy: str, diagnosis: dict, content: str) -> dict | None:
    """
    Generate a bounded mutation based on diagnosis.
    Returns mutation dict or None if no valid mutation possible.
    """
    skill_md = resolve_skill_path(skill_name)
    if skill_md is None:
        print(f"  ⚠️  Cannot generate mutation: skill '{skill_name}' not found on disk")
        return None
    skill_dir = skill_md.parent
    
    # Parse frontmatter
    lines = content.split("\n")
    fm_end = 0
    if lines and lines[0].strip() == "---":
        for i, line in enumerate(lines[1:], 1):
            if line.strip() == "---":
                fm_end = i + 1
                break
    body = "\n".join(lines[fm_end:])
    
    mutation = {
        "skill": skill_name,
        "strategy": strategy,
        "diagnosis": diagnosis["primary_mode"],
        "confidence": diagnosis["confidence"],
    }
    
    if strategy == "extend":
        # Add missing sections — domain-aware content based on skill name/desc
        sections_to_add = []
        desc_lower = skill_name.replace("-", " ").replace("_", " ")
        
        if diagnosis["primary_mode"] == "missing_structure":
            if not re.search(r"^#{1,3}\s+steps", body, re.MULTILINE | re.IGNORECASE):
                sections_to_add.append(
                    f"## Steps\n\n"
                    f"1. **Analyze** — Determine the scope and requirements for {desc_lower}\n"
                    f"2. **Prepare** — Gather necessary inputs, validate preconditions\n"
                    f"3. **Execute** — Run the core operation using appropriate tools\n"
                    f"4. **Verify** — Confirm the output matches expected results\n"
                    f"5. **Log** — Record actions taken for audit trail"
                )
            if not re.search(r"^#{1,3}\s+pitfall", body, re.MULTILINE | re.IGNORECASE):
                sections_to_add.append(
                    "## Pitfalls\n\n"
                    "- Validate all inputs before processing — malformed data should fail fast\n"
                    "- Handle concurrent access: lock resources before mutation\n"
                    "- Timeout protection: set max execution time, retry with backoff\n"
                    "- Always log errors with full context for debugging"
                )
        
        elif diagnosis["primary_mode"] == "missing_edge_cases":
            sections_to_add.append(
                "## Error Handling\n\n"
                "- **Missing input**: Return early with descriptive error message\n"
                "- **Partial failure**: Roll back completed steps, report what succeeded\n"
                "- **Permission denied**: Escalate with full context and suggested fix\n"
                "- **Timeout**: Retry up to 3 times with exponential backoff\n"
                "- **Corrupted state**: Verify integrity before continuing"
            )
        
        elif diagnosis["primary_mode"] == "missing_tool_step":
            sections_to_add.append(
                f"## Tool Usage\n\n"
                f"For {desc_lower}, use these tools in sequence:\n\n"
                f"1. **Inspect** — Use `read_file` or `search_files` to examine current state\n"
                f"2. **Modify** — Use `patch` or `write_file` for targeted changes\n"
                f"3. **Validate** — Verify the change with a follow-up read or test\n"
                f"4. **Document** — Log what changed and why"
            )
        
        if sections_to_add:
            appended = "\n\n" + "\n\n".join(sections_to_add)
            mutation.update({
                "edit_type": "append",
                "appended_content": appended,
                "old_string": content.rstrip()[-100:],  # For logging
                "new_string": content.rstrip()[-100:] + appended,  # For logging
            })
            return mutation
    
    elif strategy == "repair":
        # Replace or add domain-specific content
        desc_lower = skill_name.replace("-", " ").replace("_", " ")
        
        if diagnosis["primary_mode"] == "knowledge_gap":
            # Generate domain-specific technical content based on skill domain
            # Map common skill domains to their technical terminology
            domain_terms = _get_domain_terms(skill_name, desc_lower)
            
            appended = (
                f'\n\n## Domain Context\n\n'
                f'This skill handles {desc_lower} operations.\n\n'
                f'### Key Concepts\n\n'
                f'{domain_terms}\n\n'
                f'### Workflow\n\n'
                f'1. **Initialize** — Set up config, validate environment\n'
                f'2. **Execute** — Run core operation with error handling\n'
                f'3. **Verify** — Check output integrity (checksum, test)\n'
                f'4. **Log** — Record actions to audit trail with timestamp'
            )
            mutation.update({
                "edit_type": "append",
                "appended_content": appended,
                "old_string": content.rstrip()[-100:],
                "new_string": content.rstrip()[-100:] + appended,
            })
            return mutation
        
        elif diagnosis["primary_mode"] == "missing_tool_step":
            appended = (
                f"\n\n## Execution Steps\n\n"
                f"1. Parse the task requirements for {desc_lower}\n"
                f"2. Select appropriate tools from the available toolset\n"
                f"3. Execute in sequence, verifying each step\n"
                f"4. Handle errors gracefully with fallback strategies"
            )
            mutation.update({
                "edit_type": "append",
                "appended_content": appended,
                "old_string": content.rstrip()[-100:],
                "new_string": content.rstrip()[-100:] + appended,
            })
            return mutation
    
    elif strategy == "compress":
        # Identify and remove fluff sections
        # For v2, we target sections that are mostly generic sentences
        sections = re.split(r"(^#{1,3}\s+.+$)", body, flags=re.MULTILINE)
        sections_to_remove = []
        
        for i, section in enumerate(sections):
            if section.startswith("#") and i + 1 < len(sections):
                section_body = sections[i + 1]
                if _is_generic_content(section_body) and len(section_body.split()) > 30:
                    sections_to_remove.append((section, section_body))
        
        if sections_to_remove:
            # Remove the first fluff section found
            target_header, target_body = sections_to_remove[0]
            old_string = target_header + target_body
            mutation.update({
                "edit_type": "remove",
                "old_string": old_string.strip(),
                "new_string": "",
                "removed_section": target_header.strip(),
            })
            return mutation
    
    elif strategy == "actionability_patch":
        # Inject concrete executable examples — code blocks, CLI commands, tool calls
        desc_lower = skill_name.replace("-", " ").replace("_", " ")
        # Map skill domains to realistic tool/command examples
        examples = _get_actionability_examples(skill_name, desc_lower)
        if examples:
            appended = f"\n\n## Examples\n\n{examples}"
            mutation.update({
                "edit_type": "append",
                "appended_content": appended,
                "old_string": content.rstrip()[-100:],
                "new_string": content.rstrip()[-100:] + appended,
            })
            return mutation
    
    # Fallback: no mutation possible
    return None


def _get_actionability_examples(skill_name: str, desc_lower: str) -> str | None:
    """Generate domain-appropriate executable examples (code blocks, CLI, tool calls).
    
    Returns markdown-formatted examples section content, or None if no examples match.
    Injects concrete commands, tool call patterns, and file paths — the elements
    that the actionability benchmark measures.
    """
    name_lower = skill_name.lower()
    
    # Map keyword clusters to executable examples
    example_map = [
        # Coding / software development
        (["python", "code", "script", "writ", "terminal", "bash"], 
         "```bash\n# Run the skill's workflow\npython scripts/skill_exec.py --mode validate\n\n# Verify output\ncat output/results.json | python -m json.tool\n```\n```python\nfrom pathlib import Path\n\n# Core pattern\nresult = process_input(source_data)\nif result.status == \"ok\":\n    save_to_vault(result.content, result.metadata)\n```"),
        
        # Git / version control
        (["git", "github", "pull", "commit", "repo", "branch", "pr"],
         "```bash\n# Clone and prepare\ngh repo clone org/repo\ncd repo\ngit checkout -b feature/my-feature\n\n# Create PR\ngh pr create --title \"Fix: ...\" --body \"Closes #...\"\ngh pr review --approve --comment \"LGTM\"\n```"),
        
        # File / vault operations
        (["file", "vault", "read", "write", "path", "search", "obsidian", "note"],
         "```bash\n# Search vault for topic\nrg -l \"first-principles\" D:/PhronesisVault/\n\n# Extract key files\npython -c \"\nimport json\nfrom pathlib import Path\nvault = Path('D:/PhronesisVault')\nfor f in vault.rglob('*.md'):\n    print(f.relative_to(vault))\n\" | head -20\n```"),
        
        # Research / ArXiv
        (["arxiv", "research", "paper", "scholar", "search"],
         "```bash\n# Search recent papers\npython -c \"\nimport urllib.request, xml.etree.ElementTree as ET\nquery = 'cat:cs.AI+AND+ti:reasoning'\nurl = f'http://export.arxiv.org/api/query?search_query={query}&max_results=5'\nroot = ET.fromstring(urllib.request.urlopen(url).read())\nfor entry in root.findall('{http://www.w3.org/2005/Atom}entry'):\n    print(entry.find('{http://www.w3.org/2005/Atom}title').text)\n\"\n```\n```bash\n# Download and extract\ncurl -O https://arxiv.org/pdf/2401.00001.pdf\npython -m marker_pdf 2401.00001.pdf output/\n```"),
        
        # Machine learning / inference
        (["model", "train", "infer", "llm", "gguf", "quantiz", "hf", "hugging"],
         "```bash\n# List available models\nollama list\n\n# Inference with custom params\ncurl http://localhost:8091/v1/completions \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"model\": \"qwen2.5-coder\", \"prompt\": \"Explain first-principles reasoning\", \"max_tokens\": 200}' \\\n  | python -m json.tool\n\n# Benchmark tokens/s\npython -c \"\nimport time, requests\nt0 = time.time()\nresp = requests.post('http://localhost:8091/v1/completions',\n    json={'model':'default','prompt':'Hello ' * 50,'max_tokens':100})\ntps = 100 / (time.time() - t0)\nprint(f'{tps:.1f} tokens/s')\n\"\n```"),
        
        # Web / browser
        (["browser", "web", "navigate", "click", "scrape", "url"],
         "```bash\n# Load page and extract content\npython -c \"\nimport requests\nfrom bs4 import BeautifulSoup\nresp = requests.get('https://example.com')\nsoup = BeautifulSoup(resp.text, 'html.parser')\nfor h2 in soup.find_all('h2'):\n    print(h2.text.strip())\n\"\n```\n```bash\n# Check page status\ncurl -sI https://example.com | head -5\n```"),
        
        # Monitoring / logging / observability
        (["monitor", "log", "observ", "metric", "health", "alert", "dashboard"],
         "```bash\n# Check service health\ncurl -s http://localhost:8091/health | python -m json.tool\n\n# Tail recent logs\ntail -n 50 D:/HermesData/logs/hermes.log | grep -i error | head -10\n\n# Resource usage\npython -c \"\nimport psutil\nmem = psutil.virtual_memory()\nprint(f'CPU: {psutil.cpu_percent(interval=1)}%')\nprint(f'RAM: {mem.percent}% ({mem.used // 1024**3}GB/{mem.total // 1024**3}GB)')\n\"\n```"),
        
        # Database / data
        (["sql", "database", "db", "query", "data", "json", "csv", "yaml"],
         "```bash\n# Query with sqlite\npython -c \"\nimport sqlite3\nconn = sqlite3.connect('data.db')\ncursor = conn.execute('SELECT name, COUNT(*) FROM records GROUP BY name ORDER BY 2 DESC LIMIT 5')\nfor row in cursor:\n    print(f'{row[0]}: {row[1]}')\n\"\n\n# Parse JSON data\ncat data.json | python -c \"import json,sys; d=json.load(sys.stdin); print(json.dumps(d, indent=2))\" | head -30\n```"),
        
        # Media / image generation
        (["image", "comfy", "video", "media", "style", "render", "pixel"],
         "```bash\n# Check ComfyUI status\ncurl -s http://localhost:8189/api/system/stats | jq .\n\n# Run inference\npython -c \"\nimport requests\nresp = requests.post('http://localhost:8189/api/prompt',\n    json={'prompt': {'3': {'inputs': {'seed': 42}, 'class_type': 'KSampler'}}})\nprint(resp.json())\n\"\n```"),
        
        # Smart home / IoT
        (["hue", "light", "home", "iot", "sensor", "zigbee"],
         "```bash\n# List lights\npython -c \"\nimport requests\nresp = requests.get('http://localhost/api/lights')\nfor light in resp.json():\n    print(f'{light[\\\"name\\\"]}: {light[\\\"state\\\"][\\\"on\\\"]}')\n\"\n\n# Toggle scene\ncurl -X PUT http://localhost/api/scenes/cozy/action -d '{\"on\": true}'\n```"),
        
        # Backup / restore
        (["backup", "restore", "snapshot", "archive", "zip", "tar"],
         "```bash\n# Create backup\npython -c \"\nimport zipfile, os\nos.makedirs('backups', exist_ok=True)\nwith zipfile.ZipFile('backups/vault-2026-07-01.zip', 'w', zipfile.ZIP_DEFLATED) as zf:\n    for root, dirs, files in os.walk('D:/PhronesisVault'):\n        for f in files:\n            zf.write(os.path.join(root, f))\nprint('Backup created')\n\"\n\n# Verify backup\npython -c \"\nimport zipfile\nwith zipfile.ZipFile('backups/vault-2026-07-01.zip', 'r') as zf:\n    info = zf.testzip()\n    print(f'Integrity: {\\\"OK\\\" if info is None else \\\"CORRUPT\\\"}')\n    print(f'Files: {len(zf.namelist())}')\n\"\n```"),
    ]
    
    # Find matching domain
    for keywords, example in example_map:
        if any(k in name_lower or k in desc_lower for k in keywords):
            return example
    
    # Fallback: generate a generic but still actionable example
    fallback = (
        "```bash\n"
        "# Inspect current state\n"
        f"ls -la D:/HermesData/skills/{skill_name}/\n"
        "\n"
        "# Validate skill\n"
        "python3 -c \"\n"
        f"import pathlib; p = pathlib.Path('D:/HermesData/skills/{skill_name}/SKILL.md');\n"
        "print(f'Found: {p.stat().st_size}B' if p.exists() else 'Not found')\n"
        "\"\n"
        "```"
    )
    return fallback


# ─── Gate (3-Layer) ──────────────────────────────────────────────────────────

def gate_pre_check(mutation: dict, content: str) -> tuple[bool, str]:
    """
    Layer 1: Cheap deterministic pre-checks.
    Returns (passed, reason).
    """
    # Check 1: Not generic
    if mutation["edit_type"] == "append":
        appended = mutation.get("appended_content", "")
        if _is_generic_content(appended):
            return False, "Mutation content is generic filler (tautology detected)"
    
    # Check 2: Size bound (relaxed for very small skills that need minimum viable content)
    if mutation["edit_type"] == "append":
        appended = mutation.get("appended_content", "")
        max_size = max(600, len(content) * MAX_MUTATION_RATIO)  # At least 600 chars for small skills
        if len(appended) > max_size:
            return False, f"Mutation too large: {len(appended)} chars > {max_size:.0f} max"
    
    # Check 3: No duplicate content
    if mutation["edit_type"] == "append":
        appended = mutation.get("appended_content", "")
        # Check if key content already exists (bullet/line-level comparison)
        appended_lines = set(l.strip().lower() for l in appended.split('\n') if len(l.strip()) > 15 and l.strip().startswith(('-', '*', '##')))
        content_lines = set(l.strip().lower() for l in content.split('\n') if len(l.strip()) > 15 and l.strip().startswith(('-', '*', '##')))
        overlap = appended_lines & content_lines
        if len(appended_lines) > 0 and len(overlap) > len(appended_lines) * 0.3:
            return False, f"Mutation content already in skill ({len(overlap)} lines overlap with existing)"
    
    return True, "Pre-check passed"


def gate_benchmark(
    skill_name: str,
    mutation: dict,
    old_benchmarks: dict[str, float],
    target_benchmark: str,
) -> tuple[bool, str, dict]:
    """
    Layer 2: Run benchmarks on mutated skill.
    Returns (passed, reason, new_benchmarks).
    """
    skill_md = resolve_skill_path(skill_name)
    if skill_md is None:
        return False, f"Skill '{skill_name}' not found on disk", old_benchmarks
    content = skill_md.read_text(encoding="utf-8")
    
    # Apply mutation temporarily
    backup = content
    if mutation["edit_type"] == "append":
        new_content = content.rstrip() + mutation["appended_content"]
    elif mutation["edit_type"] == "remove":
        new_content = content.replace(mutation["old_string"], mutation["new_string"])
    else:
        return False, f"Unknown edit_type: {mutation['edit_type']}", old_benchmarks
    
    # Write temp version
    skill_md.write_text(new_content, encoding="utf-8")
    
    # Run benchmarks
    new_benchmarks = run_benchmarks(skill_md)
    
    # Restore original
    skill_md.write_text(backup, encoding="utf-8")
    
    # Check target benchmark improved
    old_target = old_benchmarks.get(target_benchmark, 0)
    new_target = new_benchmarks.get(target_benchmark, 0)
    delta = new_target - old_target
    
    if delta < MIN_DELTA:
        return False, f"Target benchmark '{target_benchmark}' delta={delta:.3f} < {MIN_DELTA}", new_benchmarks
    
    # Check no regression on other benchmarks
    for bench, old_score in old_benchmarks.items():
        if bench == target_benchmark:
            continue
        new_score = new_benchmarks.get(bench, 0)
        if new_score < old_score - REGRESSION_TOLERANCE:
            return False, f"Regression on '{bench}': {old_score:.3f} → {new_score:.3f}", new_benchmarks
    
    return True, f"Target '{target_benchmark}' improved {old_target:.3f} → {new_target:.3f} (Δ={delta:.3f})", new_benchmarks


def resolve_skill_path(skill_name: str, skill_map: dict[str, Path] = None) -> Path | None:
    """Resolve a skill name to its SKILL.md path, handling nested subdirectories.
    
    Previously assumed all skills were at skills/<name>/SKILL.md, which failed
    for skills in category subdirs (skills/mlops/<name>/SKILL.md).
    """
    if skill_map is None:
        skill_map = _build_skill_map()
    skill_md = skill_map.get(skill_name)
    if skill_md and skill_md.parent and skill_md.exists():
        return skill_md
    # Fallback to old direct path (for backward compat during transition)
    fallback = SKILLS_DIR / skill_name / "SKILL.md"
    if fallback.exists():
        return fallback
    return None


def gate_structural(skill_name: str) -> tuple[bool, str]:
    """
    Layer 3: Structural integrity check.
    Validates YAML frontmatter is properly formatted with standalone --- separators.
    """
    skill_md = resolve_skill_path(skill_name)
    if skill_md is None:
        return False, f"Skill '{skill_name}' not found on disk"
    content = skill_md.read_text(encoding="utf-8")

    # Check 1: File starts with --- separator on its own line
    if not content.startswith("---\n"):
        return False, "Frontmatter must start with '---' on its own line (got merged with content)"

    # Check 2: Find closing --- on its own line
    lines = content.split("\n")
    closing_pos = None
    for i, line in enumerate(lines[1:], 1):
        if line.strip() == "---":
            closing_pos = i
            break
    if closing_pos is None:
        return False, "Frontmatter missing closing '---' on its own line"
    if closing_pos < 3:
        return False, f"Frontmatter too short ({closing_pos} lines), needs at least name + version"

    # Check 3: Extract frontmatter and validate as YAML
    fm_text = "\n".join(lines[1:closing_pos])
    import re
    # Check for merged frontmatter separators — the critical bug that corrupted
    # monitoring-dashboard-summary. Valid YAML allows empty values (e.g. `metadata:`).
    for fm_line in fm_text.split("\n"):
        if ":" in fm_line:
            key, _, val = fm_line.partition(":")
            # Only flag merged separators inside values, not empty values
            if "---" in val and key.strip():
                return False, f"YAML value contains raw '---' (frontmatter separators merged with content on line: '{fm_line.strip()}')"

    # Check 4: Has minimum required fields  
    has_name = bool(re.search(r"^name:", fm_text, re.MULTILINE))
    has_desc = bool(re.search(r"^description:", fm_text, re.MULTILINE))
    if not has_name:
        return False, "Frontmatter missing 'name' field"
    if not has_desc:
        return False, "Frontmatter missing 'description' field (required for discoverability)"

    # Check 5: Body not empty
    body = "\n".join(lines[closing_pos + 1:])
    if len(body.strip()) < 50:
        return False, f"Skill body too short ({len(body.strip())} chars < 50 min)"

    return True, "Structural check passed"


# ─── Commit ──────────────────────────────────────────────────────────────────

def commit_mutation(skill_name: str, mutation: dict, new_benchmarks: dict):
    """Finalize mutation — file already has mutation applied from Layer 3 check.
    Only bumps version and logs. Does NOT re-apply edit to avoid duplication."""
    skill_md = resolve_skill_path(skill_name)
    if skill_md is None:
        print(f"  ⚠️  Cannot commit mutation for '{skill_name}': skill not found on disk")
        return
    new_content = skill_md.read_text(encoding="utf-8")
    
    # Bump version in frontmatter (idempotent: only if not already bumped)
    version_match = re.search(r"^version:\s*(\d+)\.(\d+)", new_content, re.MULTILINE)
    if version_match:
        major, minor = int(version_match.group(1)), int(version_match.group(2))
        new_content = re.sub(
            r"^version:\s*\d+\.\d+",
            f"version: {major}.{minor + 1}",
            new_content,
            count=1,
            flags=re.MULTILINE,
        )
    
    # Write (version bump only)
    skill_md.write_text(new_content, encoding="utf-8")
    
    # Log mutation
    log_entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "skill": skill_name,
        "strategy": mutation["strategy"],
        "diagnosis": mutation["diagnosis"],
        "edit_type": mutation["edit_type"],
        "new_benchmarks": new_benchmarks,
    }
    with open(MUTATIONS_LOG, "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")
    
    print(f"  ✅ COMMITTED: {skill_name} via {mutation['strategy']} ({mutation['diagnosis']})")


def log_gate_result(skill_name: str, layer: str, passed: bool, reason: str, benchmarks: dict = None):
    """Log gate decision."""
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "skill": skill_name,
        "gate_layer": layer,
        "passed": passed,
        "reason": reason,
        "benchmarks": benchmarks,
    }
    with open(GATE_LOG, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")


# ─── Snapshot & Rollback ─────────────────────────────────────────────────────

def snapshot_skill(skill_name: str, cycle: int) -> Path:
    """Create a pre-mutation snapshot."""
    skill_md = resolve_skill_path(skill_name)
    if skill_md is None:
        raise FileNotFoundError(f"Cannot snapshot '{skill_name}': skill not found on disk")
    snap_path = SNAPSHOTS_DIR / f"{skill_name}-evo-{cycle}.md"
    snap_path.write_text(skill_md.read_text(encoding="utf-8"), encoding="utf-8")
    return snap_path


def rollback_skill(skill_name: str, cycle: int):
    """Rollback to pre-mutation snapshot."""
    snap_path = SNAPSHOTS_DIR / f"{skill_name}-evo-{cycle}.md"
    if snap_path.exists():
        skill_md = resolve_skill_path(skill_name)
        if skill_md is None:
            print(f"  ⚠️  Cannot rollback '{skill_name}': skill directory missing on disk")
            return
        skill_md.write_text(snap_path.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"  ↩️  ROLLED BACK: {skill_name} to snapshot {snap_path.name}")


# ─── EGL Convergence ─────────────────────────────────────────────────────────

def update_egl(state: dict, skill_name: str, old_score: float, new_score: float) -> bool:
    """
    Update EGL history and check convergence.
    Returns True if skill has converged.
    """
    if old_score <= 0:
        egl = 0.0
    else:
        egl = (new_score - old_score) / old_score
    
    if skill_name not in state.get("egl_history", {}):
        state.setdefault("egl_history", {})[skill_name] = []
    
    state["egl_history"][skill_name].append(egl)
    
    # Check convergence: last N EGLs all below threshold
    history = state["egl_history"][skill_name]
    if len(history) >= CONVERGENCE_PATIENCE:
        recent = history[-CONVERGENCE_PATIENCE:]
        if all(abs(e) < CONVERGENCE_EGL for e in recent):
            return True
    
    return False


# ─── Main Evolution Loop ─────────────────────────────────────────────────────

def run_cycle(state: dict, dry_run: bool = False) -> dict:
    """
    Run one full evolution cycle.
    
    Phases: Observe → Diagnose → Mutate → Gate → Commit
    """
    state["cycle"] += 1
    cycle = state["cycle"]
    
    print(f"\n{'='*60}")
    print(f"  A-Evolve v2 — Cycle #{cycle}")
    print(f"  Mode: {'DRY RUN' if dry_run else 'LIVE'}")
    print(f"{'='*60}")
    
    # Phase 0a: ORPHAN CLEANUP — remove skills from state that no longer exist
    print("\n🧹 Phase 0a: Cleanup — Checking for orphaned skills...")
    state = cleanup_orphan_skills(state)
    save_state(state)
    
    # Phase 0: REGRESSION CHECK ───────────────────────────────────────
    # If a previous mutation caused overall score to drop, auto-rollback
    post_scores = state.get("post_mutation_scores", {})
    if post_scores:
        all_current = run_all_skills_benchmark()
        for skill_name, expected_score in list(post_scores.items()):
            if skill_name in all_current:
                current_score = compute_overall_score(all_current[skill_name])
                if current_score < expected_score - REGRESSION_TOLERANCE:
                    print(f"\n⚠️  REGRESSION DETECTED: {skill_name} dropped {expected_score:.3f} → {current_score:.3f}")
                    if not dry_run:
                        # Find the cycle we snapshotted at
                        snap = SNAPSHOTS_DIR / f"{skill_name}-evo-{cycle - 1}.md"
                        if snap.exists():
                            rollback_skill(skill_name, cycle - 1)
                            del post_scores[skill_name]
                            print(f"  ↩️  Auto-rolled back {skill_name}")
    
    # ─── Phase 1: OBSERVE ────────────────────────────────────────────────
    print("\n📊 Phase 1: Observe — Running benchmarks...")
    
    # Load episodic memory to blacklist failing strategies
    episodic_failures = load_episodic_memory()
    strategy_blacklist = get_strategy_blacklist(episodic_failures)
    if strategy_blacklist:
        print(f"  🧠 Episodic memory: {len(episodic_failures)} failed strategies blacklisted")
        for s in sorted(strategy_blacklist):
            print(f"     ✗ {s}: {episodic_failures[s]} failures")
    
    all_benchmarks = run_all_skills_benchmark()
    
    # Find worst-performing non-frozen, non-converged skill
    candidates = []
    for skill_name, benchmarks in all_benchmarks.items():
        if skill_name in state.get("skills_frozen", []):
            continue
        if skill_name in state.get("skills_converged", []):
            continue
        overall = compute_overall_score(benchmarks)
        candidates.append((skill_name, overall, benchmarks))
    
    if not candidates:
        print("  No candidate skills available (all frozen or converged).")
        return state
    
    # Sort by overall score ascending (worst first)
    candidates.sort(key=lambda x: x[1])
    target_skill, target_score, target_benchmarks = candidates[0]
    
    print(f"  Target: {target_skill} (overall={target_score:.3f})")
    for bench, score in sorted(target_benchmarks.items(), key=lambda x: x[1]):
        indicator = "⚠️" if score < 0.4 else "✓" if score > 0.7 else "·"
        print(f"    {indicator} {bench}: {score:.3f}")
    
    # ─── Phase 2: DIAGNOSE ───────────────────────────────────────────────
    print(f"\n🔍 Phase 2: Diagnose — Analyzing {target_skill}...")
    skill_md = resolve_skill_path(target_skill)
    if skill_md is None:
        print(f"  ⚠️  Cannot diagnose '{target_skill}': skill not found on disk")
        return state
    content = skill_md.read_text(encoding="utf-8")
    
    diagnosis = diagnose_skill(target_skill, target_benchmarks, content)
    
    if not diagnosis:
        print(f"  No clear diagnosis for {target_skill}. Freezing (may be good enough).")
        state.setdefault("skills_frozen", []).append(target_skill)
        return state
    
    print(f"  Primary failure: {diagnosis['primary_mode']} (confidence={diagnosis['confidence']:.2f})")
    print(f"  Strategy: {diagnosis['strategy']}")
    print(f"  Evidence: {diagnosis['evidence']}")
    
    # Strategy blacklist check: if the selected strategy has failed repeatedly, fall back to next
    if diagnosis["strategy"] in strategy_blacklist:
        fallback_diagnoses = [d for d in diagnosis["all_diagnoses"]
                             if FAILURE_MODES.get(d["mode"], {}).get("strategy") not in strategy_blacklist]
        if fallback_diagnoses:
            prev = diagnosis["primary_mode"]
            diagnosis["primary_mode"] = fallback_diagnoses[0]["mode"]
            diagnosis["strategy"] = FAILURE_MODES[fallback_diagnoses[0]["mode"]]["strategy"]
            diagnosis["confidence"] = fallback_diagnoses[0]["confidence"]
            print(f"  ⛔ Strategy '{FAILURE_MODES[prev]['strategy']}' blacklisted by episodic memory")
            print(f"     Fallback: {diagnosis['primary_mode']} → '{diagnosis['strategy']}'")
    
    # Save diagnosis
    diag_path = DIAGNOSIS_DIR / f"{target_skill}-cycle-{cycle}.json"
    diag_path.write_text(json.dumps(diagnosis, indent=2), encoding="utf-8")
    
    # ─── Phase 3: MUTATE ─────────────────────────────────────────────────
    print(f"\n🧬 Phase 3: Mutate — Generating {diagnosis['strategy']} mutation...")
    mutation = generate_mutation(target_skill, diagnosis["strategy"], diagnosis, content)
    
    if not mutation:
        print(f"  No valid mutation generated. Freezing {target_skill}.")
        state.setdefault("skills_frozen", []).append(target_skill)
        return state
    
    print(f"  Edit type: {mutation['edit_type']}")
    if mutation["edit_type"] == "append":
        appended_preview = mutation["appended_content"][:200].replace("\n", " ")
        print(f"  Appended: {appended_preview}...")
    
    state["mutations_attempted"] += 1

    # ─── Phase 4: GATE ───────────────────────────────────────────────────
    print(f"\n🚦 Phase 4: Gate — 3-layer validation...")
    
    # Layer 1: Pre-check
    pre_passed, pre_reason = gate_pre_check(mutation, content)
    log_gate_result(target_skill, "pre_check", pre_passed, pre_reason)
    print(f"  Layer 1 (Pre-check): {'✅' if pre_passed else '❌'} {pre_reason}")
    
    if not pre_passed:
        state["mutations_rejected"] += 1
        return state
    
    # Determine which benchmark to target
    # Map diagnosis to the most relevant benchmark
    diag_to_benchmark = {
        "missing_tool_step": "actionability",
        "knowledge_gap": "specificity",
        "verbose_fluff": "content_quality",
        "missing_structure": "structure",
        "missing_edge_cases": "actionability",
    }
    target_benchmark = diag_to_benchmark.get(diagnosis["primary_mode"], "structure")
    
    # Layer 2: Benchmark
    bench_passed, bench_reason, new_benchmarks = gate_benchmark(
        target_skill, mutation, target_benchmarks, target_benchmark
    )
    log_gate_result(target_skill, "benchmark", bench_passed, bench_reason, new_benchmarks)
    print(f"  Layer 2 (Benchmark): {'✅' if bench_passed else '❌'} {bench_reason}")
    
    if not bench_passed:
        state["mutations_rejected"] += 1
        return state
    
    # Layer 3: Structural (apply mutation first, then check)
    # Temporarily apply
    if mutation["edit_type"] == "append":
        temp_content = content.rstrip() + mutation["appended_content"]
    elif mutation["edit_type"] == "remove":
        temp_content = content.replace(mutation["old_string"], mutation["new_string"])
    else:
        temp_content = content
    
    skill_md.write_text(temp_content, encoding="utf-8")
    
    struct_passed, struct_reason = gate_structural(target_skill)
    log_gate_result(target_skill, "structural", struct_passed, struct_reason)
    print(f"  Layer 3 (Structural): {'✅' if struct_passed else '❌'} {struct_reason}")
    
    if not struct_passed:
        # Rollback
        skill_md.write_text(content, encoding="utf-8")
        print(f"  ↩️  Rolled back due to structural failure")
        state["mutations_rejected"] += 1
        return state

    if dry_run:
        print(f"\n  🔒 DRY RUN — mutation gated and bench-verified but NOT committed")
        # Rollback temp write from Layer 3 structural check
        skill_md.write_text(content, encoding="utf-8")
        return state

    # ─── Phase 5: COMMIT ────────────────────────────────────────────────
    print(f"\n💾 Phase 5: Commit — Finalizing mutation...")
    
    # Snapshot first (for potential rollback)
    snapshot_skill(target_skill, cycle)
    
    # Commit
    commit_mutation(target_skill, mutation, new_benchmarks)
    
    # Update EGL
    new_overall = compute_overall_score(new_benchmarks)
    converged = update_egl(state, target_skill, target_score, new_overall)
    
    if converged:
        print(f"  🎯 CONVERGED: {target_skill} (EGL below threshold)")
        state.setdefault("skills_converged", []).append(target_skill)
    
    state["mutations_accepted"] += 1
    state["last_target"] = target_skill
    # Post-mutation scores for next-cycle regression check
    state.setdefault("post_mutation_scores", {})[target_skill] = new_overall
    
    print(f"\n  Cycle #{cycle} complete: {target_skill} {target_score:.3f} → {new_overall:.3f}")
    
    # Check mutation budget — freeze if over budget or no improvement in 3 runs
    delta = new_overall - target_score
    over_budget = check_mutation_budget(state, target_skill, delta)
    if over_budget:
        print(f"  🧊 FREEZING {target_skill} — mutation budget exhausted ({state['mutation_budget'][target_skill]['count']} mutations)")
        state.setdefault("skills_frozen", []).append(target_skill)
    
    return state


def cleanup_orphan_skills(state: dict) -> dict:
    """Remove skills from evolution state that no longer have SKILL.md files.
    
    Prevents the engine from targeting orphaned entries and keeps the state
    file clean. Logs removals to the mutations log.
    """
    live_skills = {name for name, _ in _walk_skills(SKILLS_DIR)}
    
    # Check EGL history
    for skill_name in list(state.get("egl_history", {}).keys()):
        if skill_name not in live_skills:
            entry = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "event": "orphan_removed",
                "skill": skill_name,
                "reason": "SKILL.md no longer exists on disk",
            }
            with open(MUTATIONS_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry) + "\n")
            del state["egl_history"][skill_name]
            print(f"  🧹 Cleaned: {skill_name} removed from egl_history (orphaned)")
    
    # Check converged/frozen skills
    for key in ("skills_converged", "skills_frozen"):
        state[key] = [s for s in state.get(key, []) if s in live_skills]
    
    # Check post_mutation_scores
    for skill_name in list(state.get("post_mutation_scores", {}).keys()):
        if skill_name not in live_skills:
            del state["post_mutation_scores"][skill_name]
    
    # Clear last_target if orphaned
    if state.get("last_target") and state["last_target"] not in live_skills:
        print(f"  🧹 Cleared last_target: {state['last_target']} (orphaned)")
        state["last_target"] = None
    
    return state


# ─── CLI ─────────────────────────────────────────────────────────────────────

def ensure_dirs():
    """Create required directories."""
    for d in [EVO_DIR, SNAPSHOTS_DIR, TRAJECTORIES_DIR, DIAGNOSIS_DIR]:
        d.mkdir(parents=True, exist_ok=True)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="A-Evolve v2 — Self-improving skill evolution")
    parser.add_argument("--cycle", action="store_true", help="Run one evolution cycle")
    parser.add_argument("--dry-run", action="store_true", help="Don't apply mutations")
    parser.add_argument("--benchmark", action="store_true", help="Run benchmarks only")
    parser.add_argument("--status", action="store_true", help="Show evolution status")
    parser.add_argument("--reset", action="store_true", help="Reset evolution state")
    args = parser.parse_args()
    
    ensure_dirs()
    
    if args.reset:
        if STATE_FILE.exists():
            STATE_FILE.unlink()
        if MUTATIONS_LOG.exists():
            MUTATIONS_LOG.unlink()
        if GATE_LOG.exists():
            GATE_LOG.unlink()
        print("Evolution state reset.")
        return
    
    if args.benchmark:
        print("Running benchmarks on all skills...\n")
        results = run_all_skills_benchmark()
        for skill, benchmarks in sorted(results.items(), key=lambda x: compute_overall_score(x[1])):
            overall = compute_overall_score(benchmarks)
            print(f"{skill:40s} overall={overall:.3f}")
            for bench, score in sorted(benchmarks.items(), key=lambda x: x[1]):
                bar = "█" * int(score * 20) + "░" * (20 - int(score * 20))
                print(f"  {bench:20s} {bar} {score:.3f}")
            print()
        return
    
    if args.status:
        state = load_state()
        print(f"A-Evolve v2 Status")
        print(f"  Cycle: {state['cycle']}")
        print(f"  Mutations: {state['mutations_accepted']}/{state['mutations_attempted']} accepted")
        print(f"  Rejected: {state['mutations_rejected']}")
        print(f"  Converged: {len(state.get('skills_converged', []))} skills")
        print(f"  Frozen: {len(state.get('skills_frozen', []))} skills")
        if state.get("last_target"):
            print(f"  Last target: {state['last_target']}")
        return
    
    if args.cycle:
        state = load_state()
        state = run_cycle(state, dry_run=args.dry_run)
        save_state(state)
        return
    
    # Default: run one cycle (cron runs without --cycle flag)
    state = load_state()
    state = run_cycle(state, dry_run=False)
    save_state(state)


if __name__ == "__main__":
    main()
